---

version: "3.7"

services:
  app:
    working_dir: /app
    image: blog_engine_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ~/bundle-install:/app/vendor/bundle
    environment:
      - TZ=Asia/Tokyo
    links:
      - postgres
      - chrome

  postgres:
    image: postgres:11.2
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  chrome:
    container_name: chrome
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
