---

version: "3.7"

services:
  datastore:
    image: busybox
    volumes:
      - bundle_install:/app/vendor/bundle

  app:
    working_dir: /app
    image: blog_engine_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - bundle_install:/app/vendor/bundle
    environment:
      - TZ=Asia/Tokyo
    links:
      - postgres

  postgres:
    image: postgres:11.2
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

volumes:
  bundle_install:
    driver: local
